FROM nginx:alpine

COPY configs/nginx/discovery-nginx.conf /etc/nginx/nginx.conf
COPY data/service-responses/discovery-nginx/ /usr/share/nginx/html/

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
 CMD curl -f http://localhost:8500/services.json || exit 1