FROM nginx:alpine

LABEL maintainer="yourname@example.com"

COPY configs/nginx/gateway-nginx.conf /etc/nginx/nginx.conf
COPY data/service-responses/index.html /usr/share/nginx/html/index.html

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
 CMD curl -f http://localhost || exit 1