FROM nginx:alpine

COPY configs/nginx/user-nginx.conf /etc/nginx/nginx.conf
COPY data/service-responses/user-nginx/ /usr/share/nginx/html/

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
 CMD curl -f http://localhost:8080/users.json || exit 1