FROM nginx:alpine

ARG HTML_PATH

COPY configs/nginx/gateway-nginx.conf /etc/nginx/nginx.conf
COPY ${HTML_PATH} /usr/share/nginx/html/index.html

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
 CMD curl -f http://localhost || exit 1