FROM nginx:alpine

COPY configs/nginx/notify-nginx.conf /etc/nginx/nginx.conf
COPY data/service-responses/notify-nginx/ /usr/share/nginx/html/

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
 CMD curl -f http://localhost:8084/status.json || exit 1